[package]
name = "shieldly"
version = "0.0.1"
edition = "2024_07"
cairo-version = "2.9.4"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.9.4"
openzeppelin = "1.0.0"
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }

[dev-dependencies]
cairo_test = "2.9.4"

[[target.starknet-contract]]
casm = true
